version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: my_db_pg_container
    restart: always
    environment:
      - POSTGRES_DB=spacebear
      - POSTGRES_USER=phenyo
      - POSTGRES_PASSWORD=SAV1009@mix!
    ports:
      - '5432:5432'
    volumes:
      - ./migration:/docker-entrypoint-initdb.d/init.sql
    networks:
      - my_network
